language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: client
      before_install: cd client
      install: yarn
      script:
        - yarn test
        - yarn build
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_AUTH_TOKEN
        app: repair-my-ship
    - stage: server
      before_install: cd server
      install: yarn
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_AUTH_TOKEN
        app: repair-my-ship-api